//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Dobavljac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dobavljac()
        {
            this.Materijals = new HashSet<Materijal>();
            this.Opremas = new HashSet<Oprema>();
        }
    
        public long Id { get; set; }
        [Required(ErrorMessage = "Naziv je obavezno polje")]
        public string Naziv { get; set; }
        [Required(ErrorMessage = "Adresa je obavezno polje")]
        public string Adresa { get; set; }
        [Required(ErrorMessage = "Grad je obavezno polje")]
        public string Grad { get; set; }
        [DisplayName("Drzava")]
        public Nullable<long> Drzava { get; set; }
        [Required(ErrorMessage = "Email adresa je obavezno polje")]
        [EmailAddress(ErrorMessage = "Pogresno uneta email adresa")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Kontakt telefon je obavezno polje")]
        public string KontaktTelefon { get; set; }
        [DisplayName("Drzava")]
        public virtual Drzava Drzava1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materijal> Materijals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oprema> Opremas { get; set; }
    }
}
