//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mrpEntities : DbContext
    {
        public mrpEntities()
            : base("name=mrpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dobavljac> Dobavljacs { get; set; }
        public virtual DbSet<Drzava> Drzavas { get; set; }
        public virtual DbSet<FazaProizvodnje> FazaProizvodnjes { get; set; }
        public virtual DbSet<Materijal> Materijals { get; set; }
        public virtual DbSet<Oprema> Opremas { get; set; }
        public virtual DbSet<Proizvod> Proizvods { get; set; }
        public virtual DbSet<RadnoMesto> RadnoMestoes { get; set; }
        public virtual DbSet<Sastojak> Sastojaks { get; set; }
        public virtual DbSet<Skladiste> Skladistes { get; set; }
        public virtual DbSet<VremenaProizvodnje> VremenaProizvodnjes { get; set; }
        public virtual DbSet<Zaposleni> Zaposlenis { get; set; }
    }
}
