//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Oprema
    {
        public long Id { get; set; }
        [Required(ErrorMessage = "Naziv opreme je obavezno polje.")]
        public string Naziv { get; set; }
        [DisplayName("Datum kupovine")]
        public Nullable<System.DateTime> DatumKupovine { get; set; }
        [DisplayName("Godisnja amortizacija")]
        public Nullable<double> GodisnjaAmortizacija { get; set; }
        public Nullable<long> Dobavljac { get; set; }
        [DisplayName("Pocetna cena")]
        public Nullable<double> PocetnaCena { get; set; }
        [DisplayName("Trenutna vrednost")]
        public Nullable<double> TrenutnaVrednost { get; set; }
        [DisplayName("Dobavljac")]
        public virtual Dobavljac Dobavljac1 { get; set; }
    }
}
