//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Proizvod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvod()
        {
            this.Sastojaks = new HashSet<Sastojak>();
            this.VremenaProizvodnjes = new HashSet<VremenaProizvodnje>();
        }
    
        public long Id { get; set; }
        public string Naziv { get; set; }
        public long VremePripreme { get; set; }

        [NotMapped]
        [DisplayName("Vreme pripreme")]
        public string Vreme { get; set; }
        [NotMapped]
        public string Sastojak { get; set; }
        [NotMapped]
        public List<Materijal> Materijali { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sastojak> Sastojaks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VremenaProizvodnje> VremenaProizvodnjes { get; set; }
    }
}
