//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Sastojak
    {
        public long Id { get; set; }
        public Nullable<double> Kolicina { get; set; }
        public Nullable<long> Materijal { get; set; }
        public Nullable<long> Proizvod { get; set; }
        [NotMapped]
        public List<Materijal> Materijali { get; set; }
        public virtual Materijal Materijal1 { get; set; }
        public virtual Proizvod Proizvod1 { get; set; }
    }
}
