//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Zaposleni
    {
        public long Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public Nullable<double> Plata { get; set; }
        [DisplayName("Datum rodjenja")]
        public Nullable<System.DateTime> DatumRodjenja { get; set; }
        public string Adresa { get; set; }
        public string Grad { get; set; }
        [Display(Name = "Drzava")]
        public Nullable<long> Drzava { get; set; }
        [DisplayName("Radno mesto")]
        public Nullable<long> RadnoMesto { get; set; }
        public string Kontakt { get; set; }
        [DisplayName("Drzava")]
        public virtual Drzava Drzava1 { get; set; }
        [DisplayName("Radno mesto")]
        public virtual RadnoMesto RadnoMesto1 { get; set; }
    }
}
