//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaposleni
    {
        public long Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public Nullable<double> Plata { get; set; }
        public Nullable<System.DateTime> DatumRodjenja { get; set; }
        public string Adresa { get; set; }
        public string Grad { get; set; }
        public Nullable<long> Drzava { get; set; }
        public Nullable<long> RadnoMesto { get; set; }
        public string Kontakt { get; set; }
    
        public virtual Drzava Drzava1 { get; set; }
        public virtual RadnoMesto RadnoMesto1 { get; set; }
    }
}
